### ISSUE TITLE
include usage example

### ISSUE THREAD

**Issue by nealrs** [ghmeier/slackpay#1]
@ghmeier can you please include an example of how you'd use `/slackpay xxx yyy zzz` in the readme?

**Comment by ghmeier** [comment]
Ah yeah! I totally forgot that. Thanks for letting me know

**Comment by ghmeier** [comment]
Fixed in the latest commit: `/slackpay @username $1.00 Your venmo note.`

**Comment by nealrs** [comment]
Is that the users venmo username or their slack username?

**Comment by ghmeier** [comment]
It's the slack username

**Comment by nealrs** [comment]
thanks!!
